# Generated by Django 4.1.5 on 2023-02-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
