# Generated by Django 4.1.5 on 2023-02-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
