# Generated by Django 4.1.5 on 2023-02-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_stock_stock_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product',
            new_name='product_id',
        ),
    ]
