# Generated by Django 4.1.5 on 2023-02-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_rename_product_id_stock_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
