# Generated by Django 4.1.5 on 2023-03-01 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_remove_stock_product_delete_product_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_photo', models.FileField(upload_to='ProductDocs/')),
                ('product_des', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('stock_qty', models.IntegerField(default=0)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.category')),
                ('product_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.subcategory')),
            ],
        ),
    ]
