# Generated by Django 4.1.5 on 2023-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleshow',
            name='schedule_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
