# Generated by Django 4.1.5 on 2023-03-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0002_scheduleshow_schedule_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleshow',
            name='schedule_status',
            field=models.IntegerField(default=0),
        ),
    ]
