# Generated by Django 4.1.5 on 2023-03-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_user_dog_age'),
        ('Organisation', '0003_scheduleshow_schedule_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJudges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_name', models.CharField(max_length=50)),
                ('judge_photo', models.FileField(upload_to='OrgDocs/')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.organization')),
            ],
        ),
    ]
