# Generated by Django 4.1.5 on 2023-03-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_user_dog_age'),
        ('Organisation', '0004_addjudges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddJudges',
            new_name='AddJudge',
        ),
    ]
