from django.urls import path
from Admin import views

app_name="webadmin"
urlpatterns = [
    path('dis/', views.dis,name="dis"),
    path('deldis/<int:did>', views.Deldis,name="deldistrict"),
    path('place/', views.place,name="place"),  
    path('ajaxplace/', views.Ajaxplace,name="Ajax-Place"),
    path('delpal/<int:did>', views.Delpal,name="delplace"),
    path('cat/', views.Cat,name="Category"),
    path('delcat/<int:did>', views.DelCat,name="delcategory"),
    path('editcat/<int:eid>', views.EditCat,name="editcategory"),
    path('subcat/', views.SubCat,name="subcategory"),
    path('ajaxsub/', views.Ajaxsub,name="Ajax-Sub"),
    path('delsub/<int:did>', views.Delsub,name="delsub"),
    path('prod/', views.prod,name="prod"),
    path('delprod/<int:did>', views.Delprod,name="delprod"),
    path('user/', views.userlist,name="user"),
    path('acceptorganisation/', views.acceptlist,name="acceptorganisation"),
    path('rejectorganisation/', views.rejectlist,name="rejectorganisation"),
    path('deluser/<int:did>', views.DelUser,name="deluser"),
    path('organization/', views.orglist,name="organization"),
    # path('delorg/<int:did>', views.Delorg,name="delorg"),
    path('acceptorg/<int:did>', views.Acceptorg,name="acceptorg"),
    path('rejectorg/<int:did>', views.RejectOrg,name="rejectorg"),
    path('delorg/<int:did>', views.Delorg,name="delorg"),
    path('delorga/<int:did>', views.Delorga,name="delorga"), 
    path('addstock/<int:sid>', views.Addstock,name="addstock"), 
    path('complaint/', views.usercomplaint,name="complaint"),
    path('complaintreply/<int:cid>',views.Complaintreply,name="complaintreply"),
    path('feedback/', views.userfeedback,name="feed_back"),
    path('delfeed/<int:did>', views.DelFeed,name="delfeed"),
    path('home/',views.Home,name="Home"),
    path('report/',views.UserReport,name="report"),
    path('sreport/',views.ShowReport,name="sreport"),
    path('aprofile/',views.AdminProfile,name="aprofile"),
    path('edtpro/',views.EditProfile,name="edtpro"),
    path('Login/',views.Logout,name="Login"),
]