# Generated by Django 4.1.5 on 2023-01-23 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_category'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('org_contact', models.CharField(max_length=50)),
                ('org_email', models.CharField(max_length=50)),
                ('org_photo', models.FileField(upload_to='UserDocs/')),
                ('org_proof', models.FileField(upload_to='UserDocs/')),
                ('org_password', models.CharField(max_length=50)),
                ('org_address', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
    ]
