# Generated by Django 4.1.5 on 2023-02-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_organization_org_vstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dog_licence',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
