# Generated by Django 4.1.5 on 2023-03-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_user_dog_licence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_gender',
            new_name='dog_gender',
        ),
        migrations.AddField(
            model_name='user',
            name='dog_breed',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
