# Generated by Django 4.1.5 on 2023-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_rename_user_gender_user_dog_gender_user_dog_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dog_age',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
