# Generated by Django 4.1.5 on 2023-03-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_user_dog_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_pincode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
