# Generated by Django 4.1.5 on 2023-04-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_user_dog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dog_photo',
            field=models.FileField(null=True, upload_to='UserDocs/'),
        ),
    ]
