# Generated by Django 4.1.5 on 2023-04-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_passwrord',
            new_name='admin_password',
        ),
    ]
