# Generated by Django 4.1.5 on 2023-02-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint',
            new_name='organisation',
        ),
    ]
