# Generated by Django 4.1.5 on 2023-02-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_user_dog_licence'),
        ('User', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=50)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('organisation_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.organization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.user')),
            ],
        ),
    ]
