# Generated by Django 4.1.5 on 2023-03-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0003_scheduleshow_schedule_status'),
        ('Guest', '0004_user_dog_licence'),
        ('User', '0006_booking_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_sts', models.IntegerField(default=0)),
                ('payment_sts', models.IntegerField(default=0)),
                ('booking_date', models.DateField(auto_now=True)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organisation.scheduleshow')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.user')),
            ],
        ),
    ]
