# Generated by Django 4.1.5 on 2023-03-21 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_user_user_pincode'),
        ('User', '0007_bookshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_address', models.CharField(max_length=50)),
                ('booking_contact', models.CharField(max_length=50)),
                ('booking_pincode', models.CharField(max_length=50)),
                ('booking_amount', models.CharField(max_length=50)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.cart')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.user')),
            ],
        ),
    ]
