# Generated by Django 4.1.5 on 2023-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_remove_prodbooking_cart_prodbooking_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodbooking',
            name='booking_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
