# Generated by Django 4.1.5 on 2023-04-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_prodbooking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cart_status',
            field=models.IntegerField(default=0),
        ),
    ]
