# Generated by Django 4.1.5 on 2023-04-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_product'),
        ('User', '0011_booking_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodbooking',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.product'),
        ),
    ]
