# Generated by Django 4.1.5 on 2023-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_prodbooking_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
