# Generated by Django 4.1.5 on 2023-04-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_rename_admin_passwrord_admin_admin_password'),
        ('User', '0013_booking_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('from_org', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rom_org', to='Guest.organization')),
                ('from_user', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to='Guest.user')),
                ('to_org', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_org', to='Guest.organization')),
                ('to_user', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to='Guest.user')),
            ],
        ),
    ]
